# Codecov configuration for WalletD
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "60...90"
  
  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        target: 80%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*_test.rs"
  - "**/tests/**"
  - "**/examples/**"
  - "**/benches/**"
  - "walletd_icp_cli/**"
  - "walletd-prasaga-avio/**"

flags:
  core:
    paths:
      - crates/walletd-traits/
      - crates/walletd-core/
      - crates/walletd/
    carryforward: true
    
  bitcoin:
    paths:
      - coins/bitcoin/
    carryforward: true
    
  ethereum:
    paths:
      - coins/ethereum/
      - coins/walletd_erc20/
      - coins/base/
    carryforward: true
    
  solana:
    paths:
      - coins/solana/
    carryforward: true
    
  icp:
    paths:
      - coins/icp/
    carryforward: true
    
  hedera:
    paths:
      - coins/hedera/
    carryforward: true
    
  monero:
    paths:
      - coins/monero/
    carryforward: true
